const fs = require('node:fs');
const path = require('node:path');
const { withAppBuildGradle } = require('@expo/config-plugins');

/**
 * Sign RELEASE builds with the upload key instead of the debug key.
 *
 * 🔴 **Why a config plugin and not an edit to `android/app/build.gradle`.**
 * `app/android/` is GITIGNORED — it is a prebuild artifact. Any hand edit there
 * survives until the next `expo prebuild --clean` and then disappears, taking
 * the release signing with it. Nobody notices, because a debug-signed release
 * still builds and installs perfectly; it just cannot be uploaded to Play. A
 * plugin is re-applied on every prebuild, so the configuration cannot be lost.
 *
 * 🔴 **Credentials are NEVER in this file or in git.** They live in
 * `app/credentials/keystore.properties` (gitignored) and are read by Gradle at
 * build time. Committing a keystore password lets anyone who clones the repo
 * publish a build as us.
 *
 * ⚠️ **If the credentials are absent, release builds keep using the DEBUG key**
 * rather than failing. That is deliberate: a contributor without the key must
 * still be able to build the app. It also means "it built" is not proof it was
 * signed correctly — check with `apksigner verify --print-certs`, which is why
 * the README step exists.
 *
 * Play App Signing is in use (owner, 2026-09-25), so this is the UPLOAD key:
 * Google holds the real app-signing key and can reset this one if it is lost.
 */
const PROPS = 'credentials/keystore.properties';

const SIGNING_BLOCK = `
        release {
            // Injected by plugins/withReleaseSigning.js — do not edit here, this
            // file is regenerated by \`expo prebuild\`.
            def keystorePropertiesFile = rootProject.file('../${PROPS}')
            if (keystorePropertiesFile.exists()) {
                def keystoreProperties = new Properties()
                keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
                storeFile file("../../${PROPS.replace('keystore.properties', '')}" + keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }
`;

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (mod) => {
    let gradle = mod.modResults.contents;

    if (gradle.includes('withReleaseSigning.js')) return mod; // already applied

    // 1 · declare the release signing config next to the debug one
    gradle = gradle.replace(
      /(signingConfigs\s*\{\s*\n\s*debug\s*\{[\s\S]*?\n\s{8}\}\n)/,
      `$1${SIGNING_BLOCK}`,
    );

    // 2 · point the release build type at it. Expo's scaffold ships
    //     `signingConfig signingConfigs.debug` inside `release { … }`, which is
    //     exactly the line that makes a "release" APK unpublishable.
    gradle = gradle.replace(
      /(release\s*\{\s*\n(?:\s*\/\/[^\n]*\n)*\s*)signingConfig signingConfigs\.debug/,
      '$1signingConfig signingConfigs.release',
    );

    mod.modResults.contents = gradle;
    return mod;
  });
};
