/**
 * 🔴 SAMPLE SUPPLIERS FOR CLIENT DEMOS — NOT REAL COMPANIES.
 *
 * Owner, 2026-09-28: first "demo switch only", then the same day "put this
 * dummy data in hardcoded format, don't fetch there for now" — so `/suppliers`
 * now ALWAYS shows these, on every environment. 🔴 Before launch, wire real
 * suppliers back: fictional companies presented to real buyers as "verified"
 * would be a false trust claim on a trust marketplace. Until then the page
 * carries a "Preview data" label and is `noindex`.
 *
 * Every company AND every person here is invented. The portraits in
 * `public/suppliers/*.webp` are cut from the Phoenix cards' artwork, which the
 * owner confirmed is AI-GENERATED (2026-09-28: "phoenix ones are also
 * generated") — not photos of real people. 🔴 If that ever turns out not to be
 * true, these must be replaced: a real face on a fictional "verified" company
 * would misrepresent that person. Websites are plain text, never links.
 *
 * The extra details (capacity, turnover, languages, international presence,
 * website) exist ONLY here — owner's decision ("Demo data only for now"). Real
 * suppliers carry none of them: adding them to the public projection is a
 * separate decision (`m3-public-projection.md`), and `website` is internal.
 */
const SAMPLE = [
  {
    id: 'demo-veltora',
    person: { name: 'Arjun Mehra', role: 'Founder & Managing Director', photo: '/suppliers/veltora.webp' },
    brand: { mark: 'weave', color: '#0E5E6F' },
    name: 'Veltora Textiles',
    city: 'Tiruppur',
    region: 'Tamil Nadu',
    tagline: 'Knit fabrics and private-label garments for European and US brands.',
    category: 'Textiles, Fabrics & Yarn',
    specialities: ['Cotton knits', 'Organic cotton', 'Private label'],
    capacity: '1.2 lakh garments / month',
    turnover: '₹40–60 Cr',
    languages: ['English', 'Hindi', 'Tamil'],
    presence: ['US', 'GB', 'DE', 'AE'],
    website: 'veltoratextiles.in',
    established: 2006,
    verifiedSince: '2025-03',
    memberSince: 2024,
    highlight: { value: '19', label: 'Years exporting' },
    // Free Unsplash licence (photo-1741176505800), resized to WebP.
    image: '/supplier-veltora-factory.webp',
  },
  {
    id: 'demo-kesarvan',
    person: { name: 'Hitesh Rathod', role: 'Director, Exports', photo: '/suppliers/kesarvan.webp' },
    brand: { mark: 'leaf', color: '#8A5A12' },
    name: 'Kesarvan Agro Foods',
    city: 'Unjha',
    region: 'Gujarat',
    tagline: 'Whole and ground spices, cleaned and packed to buyer specification.',
    category: 'Agriculture',
    specialities: ['Cumin', 'Fennel', 'Turmeric'],
    capacity: '600 tonnes / month',
    turnover: '₹25–40 Cr',
    languages: ['English', 'Hindi', 'Gujarati'],
    presence: ['AE', 'US', 'SA', 'MY'],
    website: 'kesarvanagro.in',
    established: 2011,
    verifiedSince: '2025-05',
    memberSince: 2025,
    highlight: { value: '14', label: 'Export markets' },
    image: '/promo-agriculture.avif',
  },
  {
    id: 'demo-rangreza',
    person: { name: 'Vikas Shekhawat', role: 'Founder & Creative Head', photo: '/suppliers/rangreza.webp' },
    brand: { mark: 'weave', color: '#9B2C5B' },
    name: 'Rangreza Apparel House',
    city: 'Jaipur',
    region: 'Rajasthan',
    tagline: 'Block-printed womenswear and home linen, made in small, careful runs.',
    category: 'Apparel & Garments',
    specialities: ['Block print', 'Womenswear', 'Home linen'],
    capacity: '35,000 pieces / month',
    turnover: '₹10–25 Cr',
    languages: ['English', 'Hindi', 'Punjabi'],
    presence: ['US', 'FR', 'AU'],
    website: 'rangrezaapparel.in',
    established: 2014,
    verifiedSince: '2025-02',
    memberSince: 2024,
    highlight: { value: '48h', label: 'Sample dispatch' },
    image: '/promo-garments.avif',
  },
  {
    id: 'demo-aranya',
    person: { name: 'Imran Qureshi', role: 'Managing Partner', photo: '/suppliers/aranya.webp' },
    brand: { mark: 'diamond', color: '#6B3A22' },
    name: 'Aranya Leather Works',
    city: 'Kanpur',
    region: 'Uttar Pradesh',
    tagline: 'Finished leather, bags and small goods for fashion and corporate gifting.',
    category: 'Leather & Leather Products',
    specialities: ['Finished leather', 'Bags', 'Wallets'],
    capacity: '20,000 pieces / month',
    turnover: '₹25–40 Cr',
    languages: ['English', 'Hindi'],
    presence: ['IT', 'DE', 'US'],
    website: 'aranyaleather.in',
    established: 2003,
    verifiedSince: '2025-04',
    memberSince: 2024,
    highlight: { value: '22', label: 'Years exporting' },
    image: null,
  },
  {
    id: 'demo-tirthank',
    person: { name: 'Kunal Vora', role: 'Managing Director', photo: '/suppliers/tirthank.webp' },
    brand: { mark: 'hex', color: '#1F4E8C' },
    name: 'Tirthank Polymers',
    city: 'Rajkot',
    region: 'Gujarat',
    tagline: 'PVC and CPVC pipes and fittings, tested to ISO and ASTM standards.',
    category: 'Pipes, Tubes & Fittings',
    specialities: ['PVC pipes', 'CPVC fittings', 'Agri piping'],
    capacity: '900 tonnes / month',
    turnover: '₹60–100 Cr',
    languages: ['English', 'Hindi', 'Gujarati'],
    presence: ['KE', 'NG', 'AE', 'BD'],
    website: 'tirthankpolymers.in',
    established: 2009,
    verifiedSince: '2025-01',
    memberSince: 2024,
    highlight: { value: '11', label: 'Export markets' },
    image: null,
  },
  {
    id: 'demo-nilvara',
    person: { name: 'Arun Menon', role: 'Founder & CEO', photo: '/suppliers/nilvara.webp' },
    brand: { mark: 'leaf', color: '#2F6B3A' },
    name: 'Nilvara Spice Estates',
    city: 'Kochi',
    region: 'Kerala',
    tagline: 'Black pepper, cardamom and cloves from partner farms in the Western Ghats.',
    category: 'Agriculture',
    specialities: ['Black pepper', 'Cardamom', 'Cloves'],
    capacity: '250 tonnes / month',
    turnover: '₹10–25 Cr',
    languages: ['English', 'Hindi', 'Malayalam'],
    presence: ['US', 'NL', 'JP', 'AE'],
    website: 'nilvaraspice.in',
    established: 2012,
    verifiedSince: '2025-06',
    memberSince: 2025,
    highlight: { value: '100%', label: 'Traceable lots' },
    image: '/promo-agriculture.avif',
  },
  {
    id: 'demo-surajmukhi',
    person: { name: 'Rohan Deshpande', role: 'Co-founder & CEO', photo: '/suppliers/surajmukhi.webp' },
    brand: { mark: 'sun', color: '#C27A00' },
    name: 'Surajmukhi Solar Systems',
    city: 'Pune',
    region: 'Maharashtra',
    tagline: 'Solar PV modules and mounting systems for commercial rooftops.',
    category: 'Electricals — Lighting & Solar',
    specialities: ['Mono PERC modules', 'Mounting', 'Inverters'],
    capacity: '40 MW / year',
    turnover: '₹100–250 Cr',
    languages: ['English', 'Hindi', 'Marathi'],
    presence: ['AE', 'LK', 'NP', 'ZA'],
    website: 'surajmukhisolar.in',
    established: 2015,
    verifiedSince: '2025-03',
    memberSince: 2024,
    highlight: { value: '40 MW', label: 'Yearly capacity' },
    image: null,
  },
  {
    id: 'demo-devika',
    person: { name: 'Suresh Maurya', role: 'Secretary, Weavers’ Co-op', photo: '/suppliers/devika.webp' },
    brand: { mark: 'weave', color: '#7A1F3D' },
    name: 'Devika Handloom Co-op',
    city: 'Varanasi',
    region: 'Uttar Pradesh',
    tagline: 'Handwoven silk and cotton sarees, stoles and fabric by the metre.',
    category: 'Textiles, Fabrics & Yarn',
    specialities: ['Banarasi silk', 'Handloom', 'Stoles'],
    capacity: '8,000 metres / month',
    turnover: '₹5–10 Cr',
    languages: ['English', 'Hindi'],
    presence: ['US', 'GB', 'SG'],
    website: 'devikahandloom.in',
    established: 1998,
    verifiedSince: '2025-02',
    memberSince: 2024,
    highlight: { value: '27', label: 'Years weaving' },
    image: '/promo-textiles.avif',
  },
  {
    id: 'demo-marutam',
    person: { name: 'Gurpreet Sandhu', role: 'Managing Director', photo: '/suppliers/marutam.webp' },
    brand: { mark: 'gear', color: '#3B4A5A' },
    name: 'Marutam Precision Tools',
    city: 'Ludhiana',
    region: 'Punjab',
    tagline: 'Hand tools, fasteners and precision-machined components for OEMs.',
    category: 'Tools & Hardware',
    specialities: ['Hand tools', 'Fasteners', 'CNC parts'],
    capacity: '2.5 lakh units / month',
    turnover: '₹40–60 Cr',
    languages: ['English', 'Hindi', 'Punjabi'],
    presence: ['US', 'CA', 'DE', 'AU'],
    website: 'marutamtools.in',
    established: 2001,
    verifiedSince: '2025-04',
    memberSince: 2024,
    highlight: { value: '24', label: 'Years exporting' },
    image: null,
  },
  {
    id: 'demo-ojasvi',
    person: { name: 'Vikram Negi', role: 'Founder & Director', photo: '/suppliers/ojasvi.webp' },
    brand: { mark: 'drop', color: '#3E7A4F' },
    name: 'Ojasvi Herbals',
    city: 'Haridwar',
    region: 'Uttarakhand',
    tagline: 'Ayurvedic extracts, herbal powders and private-label wellness products.',
    category: 'Health & Beauty',
    specialities: ['Herbal extracts', 'Private label', 'Essential oils'],
    capacity: '120 tonnes / month',
    turnover: '₹10–25 Cr',
    languages: ['English', 'Hindi'],
    presence: ['US', 'AE', 'MY', 'GB'],
    website: 'ojasviherbals.in',
    established: 2013,
    verifiedSince: '2025-05',
    memberSince: 2025,
    highlight: { value: '300+', label: 'Formulations' },
    image: null,
  },
  {
    id: 'demo-sagarika',
    person: { name: 'Rajat Malhotra', role: 'Director, Sales', photo: '/suppliers/sagarika.webp' },
    brand: { mark: 'weave', color: '#2B5C8A' },
    name: 'Sagarika Home Textiles',
    city: 'Panipat',
    region: 'Haryana',
    tagline: 'Rugs, throws and bed linen for retailers and hospitality groups.',
    category: 'Textiles, Fabrics & Yarn',
    specialities: ['Rugs', 'Throws', 'Bed linen'],
    capacity: '50,000 pieces / month',
    turnover: '₹25–40 Cr',
    languages: ['English', 'Hindi', 'Punjabi'],
    presence: ['US', 'GB', 'SE', 'AU'],
    website: 'sagarikahome.in',
    established: 2008,
    verifiedSince: '2025-01',
    memberSince: 2024,
    highlight: { value: '17', label: 'Years exporting' },
    image: '/promo-garments.avif',
  },
  {
    id: 'demo-vistaar',
    person: { name: 'Nirav Desai', role: 'Managing Director', photo: '/suppliers/vistaar.webp' },
    brand: { mark: 'hex', color: '#8C5A1F' },
    name: 'Vistaar Packaging',
    city: 'Vapi',
    region: 'Gujarat',
    tagline: 'Corrugated cartons, printed pouches and eco-friendly jute packaging.',
    category: 'Packaging Material & Supplies',
    specialities: ['Corrugated boxes', 'Pouches', 'Jute bags'],
    capacity: '3 million units / month',
    turnover: '₹25–40 Cr',
    languages: ['English', 'Hindi', 'Gujarati'],
    presence: ['AE', 'OM', 'KE'],
    website: 'vistaarpack.in',
    established: 2016,
    verifiedSince: '2025-06',
    memberSince: 2025,
    highlight: { value: '72h', label: 'Sample dispatch' },
    image: null,
  },
];

/**
 * The sample list — HARDCODED, always returned (owner, 2026-09-28: "put this
 * dummy data in hardcoded format, don't fetch there for now"). 🔴 This replaces
 * the demo switch for now, so these fictional companies show on every
 * environment, including production, until real data is wired back.
 */
export function demoSuppliers() {
  return SAMPLE;
}
