/**
 * M2 seed data — the Category.md taxonomy (40 tops, ~260 subs) + per-top
 * CategoryAttribute defaults from MPX-Category-Form-Fields (§A25.2).
 *
 * Attribute defaults policy (owner-decided 2026-07-31):
 *  - numeric-sounding → 'number' (+ unit where obvious) · filterable
 *  - Y/N → 'boolean' · filterable
 *  - everything else → 'text' · not filterable
 *  - 'select' options are NEVER invented — those fields start as 'text' until an
 *    admin defines options in the attribute manager
 *  - required: false everywhere (admin tightens later)
 *
 * Attr tuple: [key, name, inputType, unit?]
 * Subs: a plain string, or { name, slug } where the auto-slug would collide
 * (e.g. Leather's "Footwear" vs the "Footwear" top → 'leather-footwear').
 *
 * `synonyms` are deliberately NOT here — the top-40 list is owner content
 * (Category.md: "Do NOT invent it"); entry path is the A12 admin edit.
 */

// Tops 1–34 carry goods subs; 35–39 service subs; "Other" declares its own.
export const CATALOGUE = [
  {
    name: 'Agriculture',
    attrs: [
      ['variety_type', 'Variety / type', 'text'],
      ['grade', 'Grade', 'text'],
      ['packaging_size', 'Packaging size', 'text'],
      ['shelf_life', 'Shelf life', 'text'],
      ['organic', 'Organic', 'boolean'],
      ['moisture', 'Moisture %', 'number', '%'],
    ],
    subs: [
      'Seeds & plants',
      'Grains, pulses & cereals',
      'Fresh fruits & vegetables',
      'Spices & herbs',
      'Agricultural machinery & equipment',
      'Fertilizers & soil',
      'Animal feed & fodder',
      'Cattle & livestock supplies',
      'Cold chain logistics & storage equipment',
      'Smart irrigation & drone farming tech',
    ],
  },
  {
    name: 'Apparel & Garments',
    attrs: [
      ['size', 'Size', 'text'],
      ['color', 'Color', 'text'],
      ['fabric', 'Fabric', 'text'],
      ['gender', 'Gender', 'text'],
      ['pattern', 'Pattern', 'text'],
      ['gsm', 'GSM', 'number', 'gsm'],
    ],
    subs: [
      "Men's clothing",
      "Women's clothing",
      "Kids' & infant wear",
      'Ethnic wear (sarees, kurtis, suits)',
      'Sportswear & activewear',
      'Uniforms & workwear',
      'Undergarments & hosiery',
      'Winter wear',
    ],
  },
  {
    name: 'Textiles, Fabrics & Yarn',
    attrs: [
      ['material', 'Material', 'text'],
      ['gsm', 'GSM', 'number', 'gsm'],
      ['width', 'Width', 'number'],
      ['weave', 'Weave', 'text'],
      ['color', 'Color', 'text'],
      ['pattern', 'Pattern', 'text'],
    ],
    subs: [
      'Cotton fabric',
      'Silk fabric',
      'Synthetic & blended fabric',
      'Yarn & thread',
      'Home textiles (bedsheets, towels)',
      'Dyed & printed fabric',
      'Denim',
      'Non-woven fabric',
    ],
  },
  {
    name: 'Leather & Leather Products',
    attrs: [
      ['leather_type', 'Leather type', 'text'],
      ['finish', 'Finish', 'text'],
      ['color', 'Color', 'text'],
      ['thickness', 'Thickness', 'number', 'mm'],
      ['grade', 'Grade', 'text'],
    ],
    subs: [
      'Finished leather',
      'Leather bags & wallets',
      { name: 'Footwear', slug: 'leather-footwear' }, // clashes with the "Footwear" top
      'Leather garments',
      'Belts',
      'Gloves',
      'Leather accessories',
    ],
  },
  {
    name: 'Bags, Luggage & Accessories',
    attrs: [
      ['material', 'Material', 'text'],
      ['size_capacity', 'Size / capacity', 'text'],
      ['color', 'Color', 'text'],
      ['closure_type', 'Closure type', 'text'],
      ['gender', 'Gender', 'text'],
    ],
    subs: [
      'Backpacks & school bags',
      'Travel luggage',
      'Handbags & purses',
      'Jute & cotton bags',
      'Promotional bags',
      'Belts & wallets',
    ],
  },
  {
    name: 'Footwear',
    attrs: [
      ['size', 'Size', 'text'],
      ['color', 'Color', 'text'],
      ['material', 'Material', 'text'],
      ['sole_material', 'Sole material', 'text'],
      ['gender', 'Gender', 'text'],
      ['type', 'Type', 'text'],
    ],
    subs: [
      "Men's footwear",
      "Women's footwear",
      'Sports shoes',
      'Safety & industrial shoes',
      'Sandals & slippers',
      'Footwear components',
    ],
  },
  {
    name: 'Food & Beverages',
    attrs: [
      ['weight_volume', 'Weight / volume', 'text'],
      ['packaging_type', 'Packaging type', 'text'],
      ['shelf_life', 'Shelf life', 'text'],
      ['veg_nonveg', 'Veg / non-veg', 'text'],
      ['fssai_cert', 'FSSAI cert', 'text'],
    ],
    subs: [
      'Packaged & processed food',
      'Snacks & confectionery',
      'Beverages (tea, coffee, juices)',
      'Dairy products',
      'Bakery products',
      'Edible oils',
      'Dry fruits & nuts',
      'Organic food',
    ],
  },
  {
    name: 'Chemicals, Dyes & Solvents',
    attrs: [
      ['grade', 'Grade', 'text'],
      ['purity', 'Purity %', 'number', '%'],
      ['form', 'Form (powder/liquid)', 'text'],
      ['cas_no', 'CAS no.', 'text'],
      ['application', 'Application', 'text'],
    ],
    subs: [
      'Industrial chemicals',
      'Dyes & pigments',
      'Solvents',
      'Adhesives & sealants',
      'Laboratory chemicals',
      'Agrochemicals',
      'Water treatment chemicals',
      'Specialty chemicals',
      'Bio-pesticides',
      'Organic fertilizer chemistry',
    ],
  },
  {
    name: 'Pharmaceuticals & Medical',
    attrs: [
      ['composition', 'Composition', 'text'],
      ['form', 'Form', 'text'],
      ['strength', 'Strength', 'text'],
      ['packaging', 'Packaging', 'text'],
      ['prescription', 'Prescription', 'boolean'],
    ],
    subs: [
      'Pharmaceutical formulations',
      'Ayurvedic & herbal products',
      'Surgical & medical instruments',
      'Hospital furniture & equipment',
      'Diagnostic equipment',
      'Medical disposables',
      'Nutraceuticals & supplements',
    ],
  },
  {
    name: 'Health & Beauty',
    attrs: [
      ['form', 'Form', 'text'],
      ['skin_hair_type', 'Skin / hair type', 'text'],
      ['volume', 'Volume', 'text'],
      ['fragrance', 'Fragrance', 'text'],
      ['shelf_life', 'Shelf life', 'text'],
    ],
    subs: [
      'Cosmetics & makeup',
      'Skincare products',
      'Hair care',
      'Personal hygiene',
      'Essential oils',
      'Herbal & organic beauty',
      'Salon & spa equipment',
    ],
  },
  {
    name: 'Electronics & Electrical',
    attrs: [
      ['voltage', 'Voltage', 'number', 'V'],
      ['power_rating', 'Power rating', 'number', 'W'],
      ['warranty', 'Warranty', 'text'],
      ['brand', 'Brand', 'text'],
      ['model', 'Model', 'text'],
    ],
    subs: [
      'Consumer electronics',
      'Electronic components',
      'LED lights & lighting',
      'Wires & cables',
      'Switches & sockets',
      'Batteries & power supplies',
      'CCTV & security systems',
      'Electrical panels',
    ],
  },
  {
    name: 'Industrial Machinery & Equipment',
    attrs: [
      ['power', 'Power', 'number', 'kW'],
      ['capacity', 'Capacity', 'text'],
      ['automation_grade', 'Automation grade', 'text'],
      ['voltage', 'Voltage', 'number', 'V'],
      ['phase', 'Phase', 'text'],
      ['warranty', 'Warranty', 'text'],
    ],
    subs: [
      'Manufacturing machines',
      'Packaging machines',
      'Food processing machines',
      'Printing machines',
      'Textile machinery',
      'CNC & machine tools',
      'Material handling equipment',
      'Special purpose machines',
      'Timber/wood processing machinery',
    ],
  },
  {
    name: 'Industrial Supplies',
    attrs: [
      ['material', 'Material', 'text'],
      ['size', 'Size', 'text'],
      ['grade', 'Grade', 'text'],
      ['brand', 'Brand', 'text'],
      ['application', 'Application', 'text'],
    ],
    subs: [
      'Bearings',
      'Fasteners (nuts, bolts, screws)',
      'Seals & gaskets',
      'Abrasives',
      'Lubricants & oils',
      'Springs',
      'Industrial belts',
      'Hand & power tools',
    ],
  },
  {
    name: 'Mechanical Parts & Spares',
    attrs: [
      ['material', 'Material', 'text'],
      ['size', 'Size', 'text'],
      ['type', 'Type', 'text'],
      ['application', 'Application', 'text'],
      ['brand', 'Brand', 'text'],
    ],
    subs: ['Pumps', 'Valves', 'Motors', 'Gears & gearboxes', 'Compressors', 'Hydraulic & pneumatic parts', 'Engine parts'],
  },
  {
    name: 'Automobile Parts & Spares',
    attrs: [
      ['vehicle_type', 'Vehicle type', 'text'],
      ['compatibility', 'Compatibility', 'text'],
      ['material', 'Material', 'text'],
      ['part_no', 'Part no.', 'text'],
      ['warranty', 'Warranty', 'text'],
    ],
    subs: [
      'Two-wheeler parts',
      'Car parts & accessories',
      'Commercial vehicle parts',
      'Tyres & tubes',
      'Auto electricals',
      'Lubricants',
      'Car care & wash equipment',
    ],
  },
  {
    name: 'Building & Construction',
    attrs: [
      ['material', 'Material', 'text'],
      ['grade', 'Grade', 'text'],
      ['size', 'Size', 'text'],
      ['finish', 'Finish', 'text'],
      ['strength', 'Strength', 'text'],
      ['color', 'Color', 'text'],
    ],
    subs: [
      'TMT bars & steel',
      'Cement & concrete',
      'Bricks & blocks',
      'Tiles & marble (ceramic/granite)',
      'Sanitaryware & fittings',
      'Doors & windows',
      'Paints & coatings',
      'Construction chemicals',
      'Prefab components',
    ],
  },
  {
    name: 'Pipes, Tubes & Fittings',
    attrs: [
      ['material', 'Material', 'text'],
      ['diameter_size', 'Diameter / size', 'text'],
      ['pressure_rating', 'Pressure rating', 'number', 'bar'],
      ['length', 'Length', 'text'],
      ['type', 'Type', 'text'],
    ],
    subs: ['PVC & CPVC pipes', 'GI & MS pipes', 'Pipe fittings', 'Flanges', 'Hoses', 'Tubing'],
  },
  {
    name: 'Metals, Minerals & Ores',
    attrs: [
      ['grade', 'Grade', 'text'],
      ['form', 'Form (sheet/coil/rod)', 'text'],
      ['thickness', 'Thickness', 'number', 'mm'],
      ['purity', 'Purity', 'number', '%'],
      ['dimension', 'Dimension', 'text'],
    ],
    subs: [
      'Iron & steel (casting/fabrication)',
      'Aluminium',
      'Copper & brass',
      'Stainless steel',
      'Minerals & ores',
      'Metal sheets & coils',
      'Scrap metal',
      'Precision tools & metal components (export-grade)',
    ],
  },
  {
    name: 'Plastic & PVC',
    attrs: [
      ['material_type', 'Material type', 'text'],
      ['grade', 'Grade', 'text'],
      ['color', 'Color', 'text'],
      ['thickness', 'Thickness', 'number', 'mm'],
      ['application', 'Application', 'text'],
    ],
    subs: [
      'Plastic granules & raw material',
      'Plastic containers & crates',
      'Plastic sheets & films',
      'PVC products',
      'Plastic water tanks',
      'Moulded plastic products',
    ],
  },
  {
    name: 'Rubber & Rubber Products',
    attrs: [
      ['material', 'Material', 'text'],
      ['hardness', 'Hardness (shore)', 'number', 'shore'],
      ['color', 'Color', 'text'],
      ['size', 'Size', 'text'],
      ['application', 'Application', 'text'],
    ],
    subs: ['Rubber sheets', 'Rubber seals & gaskets', 'Rubber hoses', 'Tyres', 'Rubber components', 'Latex products'],
  },
  {
    name: 'Packaging Material & Supplies',
    attrs: [
      ['material', 'Material', 'text'],
      ['size', 'Size', 'text'],
      ['capacity', 'Capacity', 'text'],
      ['printing', 'Printing', 'boolean'],
      ['type', 'Type', 'text'],
    ],
    subs: [
      'Corrugated boxes & cartons',
      'PET bottles & jars',
      'Pouches & films',
      'Labels & stickers',
      'Paper bags',
      'Packaging tapes',
      'Bottle caps & closures',
      'Jute/cotton eco-packaging',
    ],
  },
  {
    name: 'Paper & Paper Products',
    attrs: [
      ['gsm', 'GSM', 'number', 'gsm'],
      ['size', 'Size', 'text'],
      ['type', 'Type', 'text'],
      ['color', 'Color', 'text'],
      ['brightness', 'Brightness', 'number'],
    ],
    subs: [
      'Copier & printing paper',
      'Kraft paper',
      'Paper plates & cups',
      'Tissue paper',
      'Notebooks & registers',
      'Paperboard',
    ],
  },
  {
    name: 'Furniture & Furnishings',
    attrs: [
      ['material', 'Material', 'text'],
      ['dimensions', 'Dimensions', 'text'],
      ['color_finish', 'Color / finish', 'text'],
      ['type', 'Type', 'text'],
      ['capacity', 'Capacity', 'text'],
    ],
    subs: [
      'Office furniture',
      'Home furniture',
      'Modular furniture',
      'Outdoor furniture',
      'Mattresses',
      'Curtains & upholstery',
    ],
  },
  {
    name: 'Home & Kitchen',
    attrs: [
      ['material', 'Material', 'text'],
      ['capacity_size', 'Capacity / size', 'text'],
      ['color', 'Color', 'text'],
      ['type', 'Type', 'text'],
      ['brand', 'Brand', 'text'],
    ],
    subs: [
      'Kitchenware & cookware',
      'Home decor',
      'Cleaning supplies',
      'Storage & organizers',
      'Crockery & tableware',
      'Small appliances',
    ],
  },
  {
    name: 'Gems & Jewellery',
    attrs: [
      ['metal', 'Metal', 'text'],
      ['purity_karat', 'Purity (karat)', 'number', 'karat'],
      ['weight', 'Weight', 'number', 'g'],
      ['stone_type', 'Stone type', 'text'],
      ['design', 'Design', 'text'],
    ],
    subs: [
      'Gold & silver jewellery',
      'Imitation jewellery',
      'Precious & semi-precious stones',
      'Diamond jewellery',
      'Jewellery-making supplies',
    ],
  },
  {
    name: 'Handicrafts & Decoratives',
    attrs: [
      ['material', 'Material', 'text'],
      ['size', 'Size', 'text'],
      ['color', 'Color', 'text'],
      ['theme', 'Theme', 'text'],
      ['handmade', 'Handmade', 'boolean'],
    ],
    subs: [
      'Handicraft items',
      'Wall decor & paintings',
      'Religious items',
      'Gift articles',
      'Candles & fragrances',
      'Artificial flowers',
    ],
  },
  {
    name: 'Sports, Toys & Games',
    attrs: [
      ['material', 'Material', 'text'],
      ['age_group', 'Age group', 'text'],
      ['size', 'Size', 'text'],
      ['type', 'Type', 'text'],
      ['brand', 'Brand', 'text'],
    ],
    subs: ['Sports equipment', 'Fitness & gym equipment', 'Toys & games', 'Outdoor & adventure gear', 'Musical instruments'],
  },
  {
    name: 'Tools & Hardware',
    attrs: [
      ['material', 'Material', 'text'],
      ['size', 'Size', 'text'],
      ['type', 'Type', 'text'],
      ['power', 'Power (if any)', 'text'],
      ['brand', 'Brand', 'text'],
    ],
    subs: ['Hand tools', 'Power tools', 'Cutting tools', 'Measuring instruments', 'Hardware fittings', 'Welding equipment'],
  },
  {
    name: 'Safety & Security',
    attrs: [
      ['type', 'Type', 'text'],
      ['material', 'Material', 'text'],
      ['size', 'Size', 'text'],
      ['certification', 'Certification / standard', 'text'],
      ['application', 'Application', 'text'],
    ],
    subs: [
      'Personal protective equipment (PPE)',
      'Fire safety',
      'Safety shoes & helmets',
      'Surveillance systems',
      'Access control',
      'Industrial PPE & safety gear',
    ],
  },
  {
    name: 'Scientific & Lab Instruments',
    attrs: [
      ['type', 'Type', 'text'],
      ['range_accuracy', 'Range / accuracy', 'text'],
      ['power', 'Power', 'text'],
      ['brand', 'Brand', 'text'],
      ['application', 'Application', 'text'],
    ],
    subs: ['Laboratory equipment', 'Testing & measuring instruments', 'Microscopes', 'Analytical instruments', 'Lab glassware'],
  },
  {
    name: 'Electricals — Lighting & Solar',
    attrs: [
      ['wattage', 'Power / wattage', 'number', 'W'],
      ['voltage', 'Voltage', 'number', 'V'],
      ['type', 'Type', 'text'],
      ['efficiency', 'Efficiency', 'number', '%'],
      ['warranty', 'Warranty', 'text'],
    ],
    subs: [
      'Solar PV panels & systems',
      'Inverters & batteries',
      'Lithium battery storage',
      'LED & lighting fixtures',
      'Street & industrial lighting',
      'Renewable energy equipment',
      'Green hydrogen equipment',
    ],
  },
  {
    name: 'Environment & Water',
    attrs: [
      ['capacity', 'Capacity', 'text'],
      ['type', 'Type', 'text'],
      ['power', 'Power', 'text'],
      ['technology', 'Technology', 'text'],
      ['application', 'Application', 'text'],
    ],
    subs: [
      'Water treatment plants',
      'RO & purification systems',
      'Pollution control equipment',
      'Waste management',
      'Air filtration',
    ],
  },
  {
    name: 'Office Supplies & Stationery',
    attrs: [
      ['type', 'Type', 'text'],
      ['size', 'Size', 'text'],
      ['color', 'Color', 'text'],
      ['material', 'Material', 'text'],
      ['brand', 'Brand', 'text'],
    ],
    subs: [
      'Stationery items',
      'Printing & promotional products',
      'Office equipment',
      'Files & folders',
      'Writing instruments',
    ],
  },
  {
    name: 'Telecom & Mobile',
    attrs: [
      ['type', 'Type', 'text'],
      ['brand', 'Brand', 'text'],
      ['model', 'Model', 'text'],
      ['key_specs', 'Key specs', 'text'],
      ['warranty', 'Warranty', 'text'],
    ],
    subs: [
      'Mobile phones & accessories',
      'Telecom equipment',
      'Signal boosters',
      'Networking devices',
      'Cables & connectors',
    ],
  },
  {
    name: 'IT, Software & AI Services',
    attrs: [
      ['service_type', 'Service type', 'text'],
      ['tech_stack', 'Tech stack', 'text'],
      ['engagement', 'Engagement (project/hourly/dedicated)', 'text'],
      ['team_size', 'Team size', 'number'],
      ['delivery', 'Delivery (remote/onsite)', 'text'],
      ['timeline', 'Timeline', 'text'],
    ],
    subs: [
      'Custom AI/ML & Generative AI (LLM) development',
      'Mobile app development (iOS/Android)',
      'Web & e-commerce development',
      'Cloud migration & DevOps (AWS/Azure/GCP)',
      'ERP implementation (SAP/Oracle)',
      'Cybersecurity & data privacy services',
      'Blockchain & Web3 development',
      'Legacy code modernization (COBOL/Java)',
      'Outsourced technical support (L1/L2)',
    ],
  },
  {
    name: 'Finance, Accounting & Business Process Services',
    attrs: [
      ['service_type', 'Service type', 'text'],
      ['compliance', 'Compliance (ISO/GDPR)', 'text'],
      ['engagement', 'Engagement', 'text'],
      ['team_size', 'Team size', 'number'],
      ['delivery', 'Delivery', 'text'],
      ['turnaround', 'Turnaround', 'text'],
    ],
    subs: [
      'Offshore accounting & bookkeeping',
      'Tax preparation & compliance (ATO/IRS etc.)',
      'Fractional CFO & financial advisory',
      'SMSF / pension fund outsourcing',
      'AI-led finance automation (AP/AR)',
      'ISO/GDPR-compliant BPO / back-office teams',
      'Legal process outsourcing (LPO)',
    ],
  },
  {
    name: 'Healthcare & Clinical Services',
    attrs: [
      ['service_type', 'Service type', 'text'],
      ['specialization', 'Specialization', 'text'],
      ['compliance', 'Compliance / cert', 'text'],
      ['engagement', 'Engagement', 'text'],
      ['delivery', 'Delivery', 'text'],
      ['timeline', 'Timeline', 'text'],
    ],
    subs: [
      'Clinical data management & R&D outsourcing',
      'Medical device contract manufacturing (as a service)',
      'Telemedicine platform development',
      'Biotech lab outsourcing',
    ],
  },
  {
    name: 'Education, Training & EdTech',
    attrs: [
      ['program_type', 'Program type', 'text'],
      ['mode', 'Mode (online/offline)', 'text'],
      ['duration', 'Duration', 'text'],
      ['certification', 'Certification', 'text'],
      ['language', 'Language', 'text'],
      ['batch_size', 'Batch size', 'number'],
    ],
    subs: [
      'Vocational/technical training partnerships',
      'EdTech content & LMS platforms',
      'Professional certification training',
      'Language & communication coaching',
    ],
  },
  {
    name: 'Marketing, Design & Digital Services',
    attrs: [
      ['service_type', 'Service type', 'text'],
      ['deliverables', 'Deliverables', 'text'],
      ['engagement', 'Engagement', 'text'],
      ['turnaround', 'Turnaround', 'text'],
      ['tools_platforms', 'Tools / platforms', 'text'],
      ['revisions', 'Revisions', 'number'],
    ],
    subs: [
      'Digital marketing & AI personalization',
      '3D modeling & product prototyping (design service)',
      'Content/creative production',
    ],
  },
  {
    // A14: "Other" seeds exactly two TYPED subs; A17: small FIXED attribute set,
    // no free-form mechanism anywhere. (Set = Specification + Application —
    // flagged owner default, plan §6.)
    name: 'Other',
    attrs: [
      ['specification', 'Specification', 'text'],
      ['application', 'Application', 'text'],
    ],
    subs: [
      { name: 'Other goods', type: 'goods' },
      { name: 'Other services', type: 'service' },
    ],
  },
];

// Tops 1–34 = goods subs, 35–39 = service subs (index-based; "Other" declares
// per-sub types explicitly).
export function subTypeForTopIndex(index) {
  return index < 34 ? 'goods' : 'service';
}
